# Site settings
name: SMUG Romania

email: contact@smug.ro

#url: "http://yourdomain.com" # the base hostname & protocol for your site

twitter_username: smugro
github_username:  smugro
facebook_group: smugro

# Build settings
markdown: kramdown
