# Site settings
name: SMUG Romania

email: contact@smug.ro

#url: "http://yourdomain.com" # the base hostname & protocol for your site

twitter_username: scugro
github_username:  scugro
facebook_group: scugro

# Build settings
markdown: kramdown
